#flyway:
#    url: jdbc:mysql://127.0.0.1:3308/auto-test?useUnicode=true&characterEncoding=UTF-8
#    user: root
#    password: 1qaz!QAZ
#    driver: com.mysql.jdbc.Driver
#    locations: migration/mysql
#    baselineOnMigrate: true
#    validateOnMigrate: true
##    cleanDisabled: true
#    sqlMigrationPrefix: V
#    repeatableSqlMigrationPrefix: R
server:
  address: 127.0.0.1
  port: 8080

flyway:
  locations: migration.mysql
  baseline-on-migrate: true
  enabled: true
  out-of-order: true
  encoding: UTF-8
#  mvc:
#    static-path-pattern: /**
#  resources:
#    static-locations: classpath:/templates/
#logging:
#  level:
#    org.springframework.jdbc: INFO
#    org.springframework.transaction: INFO
#    com.kyeegroup: DEBUG
#    root: INFO
#    com.apache.ibatis: INFO
#    org.apache.tomcat.jdbc.pool.interceptor.SlowQueryReport: INFO
#  path: ./log

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/auto-test?useUnicode=true&characterEncoding=UTF-8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 1qaz!QAZ
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update



#
##    redis:
##        host: localhost
##        password: ${password}
##        port: 6379
##        pool:
##          max-idle: 100
##          min-idle: 1
##          max-active: 1000
##          max-wait: -1
##        database: 0
##        timeToLive: 1
##    c3p0:
##        jdbcUrl: jdbc:mysql://localhost:3308/auto-test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
##        user: ${username}
##        password: ${password}
##        driverClass: com.mysql.jdbc.Driver
##        minPoolSize: 2
##        maxPoolSize: 10
##        maxIdleTime: 1800000
##        acquireIncrement: 3
##        maxStatements: 1000
##        initialPoolSize: 3
##        idleConnectionTestPeriod: 60
##        acquireRetryAttempts: 30
##        acquireRetryDelay: 1000
##        breakAfterAcquireFailure: false
##        testConnectionOnCheckout: false
