#server:
#    port: 8080
#flyway:
#    url: jdbc:mysql://127.0.0.1:3308/auto-test?useUnicode=true&characterEncoding=UTF-8
#    user: root
#    password: 1qaz!QAZ
#    driver: com.mysql.jdbc.Driver
#    locations: migration/mysql
#    baselineOnMigrate: true
#    validateOnMigrate: true
##    cleanDisabled: true
#    sqlMigrationPrefix: V
#    repeatableSqlMigrationPrefix: R
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3308/auto-test?useUnicode=true&characterEncoding=UTF-8
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: 1qaz!QAZ
#
##    redis:
##        host: localhost
##        password: ${password}
##        port: 6379
##        pool:
##          max-idle: 100
##          min-idle: 1
##          max-active: 1000
##          max-wait: -1
##        database: 0
##        timeToLive: 1
##    c3p0:
##        jdbcUrl: jdbc:mysql://localhost:3308/auto-test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
##        user: ${username}
##        password: ${password}
##        driverClass: com.mysql.jdbc.Driver
##        minPoolSize: 2
##        maxPoolSize: 10
##        maxIdleTime: 1800000
##        acquireIncrement: 3
##        maxStatements: 1000
##        initialPoolSize: 3
##        idleConnectionTestPeriod: 60
##        acquireRetryAttempts: 30
##        acquireRetryDelay: 1000
##        breakAfterAcquireFailure: false
##        testConnectionOnCheckout: false
