# let thymeleaf support angularjs attribute directive
spring:
  application:
    name: auto-test
    instance_id: 001
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+08
  profiles:
      active: local
